[package]
name = "example"
version = "0.1.0"
authors = ["Sergey Ulanov <sulanov@gmail.com>"]

[features]
default = [ "sdl2" ]

sdl2 = [ "mono_display/sdl2" ]

[dependencies]
mono_display = { path = "../" }
