[package]
name = "mono_display"
version = "0.1.0"
authors = ["Sergey Ulanov <sulanov@gmail.com>"]

[features]
default = []
#default = [ "sdl2" ]

[dependencies]
rppal = "0.7.1"
font-rs = "0.1.3"
bdf = "0.5.5"
sdl2 = { version = "0.31.0", optional = true }
